# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mike Grzych
tagline:          Musings
url:              http://mikegrzych.github.io
paginate:         1
baseurl:          /
author:
  name:           Michael Grzych
  url:            https://twitter.com/grizzytron
  email:          mike.grzych@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mikegrzych
pages_list:
  About:          '/about'
  Archive:        '/archive'
  Feed:           '/atom.xml'
